language: "ruby"
sudo: false
rvm:
  - "2.3.8"
  - "2.4.5"
  - "2.5.3"
  - "2.6.1"
  - "ruby-head"
matrix:
  allow_failures:
    - rvm: "ruby-head"
before_install:
  - "gem update bundler"
  - "bin/setup"
notifications:
  email:
    - ogataken@gmail.com
